version: '3.8'

services:
  backend:
    build: ./backend
    image: yourdockerhubusername/sqnb-backend
    ports:
      - "9711:9711"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/sqnb
    depends_on:
      - db

  frontend:
    build: ./frontend
    image: yourdockerhubusername/sqnb-frontend
    ports:
      - "9710:9710"
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: sqnb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-database.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
