version: '3.8'

services:
  app:
    build: ./frontend  # 只构建前端镜像
    ports:
      - "9710:9710"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/sqnb

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: sqnb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-database.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
